$$
\text{矩阵的秩 (Rank) r(A): 指的是有效信息的行. 经过初等行变换之后, 剩下的个数就为这个矩阵的秩} \\
$$


In [1]:
import numpy as np
import scipy


matrix = np.array([[1, 2, 3, 4, 5], [11, 12, 13, 14, 15], [222, 333, 442, 244, 133], [2541, 555, 553, 777, 888], [999, 642, 777, 666, 555]])
print(f'matrix rank = {np.linalg.matrix_rank(matrix)}')


matrix rank = 5


$$
矩阵的零度 (Nullity): 指的是矩阵的解空间的维数 \\
和秩的关系：\\
\text{Rank(A) + Nullity(A) = n} \\
\text{其中，n 是矩阵的列数} \\
$$


In [2]:
matrix = np.array([[1, 2, 3, 4, 5], [11, 12, 13, 14, 15], [111, 112, 113, 114, 115], [1000, 2000, 3000, 4000, 5000], [4, 42, 77, 66, 55]])
print(f'matrix nullity = {len(matrix[0]) - np.linalg.matrix_rank(matrix)}')

matrix nullity = 2


$$
\text{矩阵的迹 (Trace) tr(A): 指方阵对角线上所有元素之和} \\
tr(A) = \sum_{i=1}^n A_{ii} \\
当A矩阵的秩为1时, 零度为n-1, 也就是说除一个元素外, 其他元素都为0, 那么 \\
tr(A) = \lambda + 0 + 0 + ... + 0 \\
tr(A) = \lambda \\
\text{其中} \lambda \text{为A的一个特征值} \\
$$


In [3]:
matrix = np.array([[1, 2, 3, 4, 5], [11, 12, 13, 14, 15], [111, 112, 113, 114, 115], [1000, 2000, 3000, 4000, 5000], [4, 42, 77, 66, 55]])
print(f'matrix trace = {np.trace(matrix)}')

matrix trace = 4181


$$
\text{矩阵的行列式 (Determinant): 指的是一个方阵的特征值的乘积, 可以用于判断矩阵是否可逆, 以及缩放比例} \\
det(A) = GaussianElimination(A) -> \text{最终得到的上三角矩阵的对角线元素的乘积} \\
det(A) != 0 \text{ 时, 矩阵可逆, 且缩放比例为 det(A)} \\
det(A) = 0 \text{ 时, 矩阵变换后, 会导致降维, 继而不可逆} \\
$$


In [4]:
matrix = np.array([[1, 2, 3, 4, 5], [11, 12, 13, 14, 15], [222, 333, 442, 244, 133], [2541, 555, 553, 777, 888], [999, 642, 777, 666, 555]])
print(f'matrix determinant = {np.linalg.det(matrix)}')


matrix determinant = 350117040.00000215


$$
\text{矩阵的逆 (Inverse): 指的是使得是n阶方阵A乘以其逆矩阵得到单位矩阵I} \\
\text{Gauss-Jordan 消元法 (初等变换): 是一种用于求解线性方程组的方法, 同时也可以用于求矩阵的逆} \\
[A|I] = [I|A^{-1}] \\
例子: \\
[A|I] = \begin{bmatrix}
1 & 2 & 3 & 1 & 0 & 0 \\
0 & 1 & 4 & 0 & 1 & 0 \\
5 & 6 & 0 & 0 & 0 & 1 \\
\end{bmatrix} \\
[I|A^{-1}] = \begin{bmatrix}
1 & 0 & 0 & -24 & 18 & 5 \\
0 & 1 & 0 & 20 & -15 & -4 \\
0 & 0 & 1 & -5 & 4 & 1 \\
\end{bmatrix} \\
$$


In [5]:
matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
print(f'matrix inverse = \n{np.linalg.inv(matrix)}')

matrix inverse = 
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


$$
矩阵乘法的数学通式 \\
C_{ij} = \sum_{k=1}^{n} A_{ik}B_{kj} \\
C = \begin{bmatrix}
    \sum_{k=1}^{n} A_{1k}B_{k1} & \sum_{k=1}^{n} A_{1k}B_{k2} & \cdots & \sum_{k=1}^{n} A_{1k}B_{kn} \\
    \sum_{k=1}^{n} A_{2k}B_{k1} & \sum_{k=1}^{n} A_{2k}B_{k2} & \cdots & \sum_{k=1}^{n} A_{2k}B_{kn} \\
    \vdots & \vdots & \ddots & \vdots \\
    \sum_{k=1}^{n} A_{nk}B_{k1} & \sum_{k=1}^{n} A_{nk}B_{k2} & \cdots & \sum_{k=1}^{n} A_{nk}B_{kn} \\
\end{bmatrix} \\
如果B是列向量 \\
C = \begin{bmatrix}
    \sum_{k=1}^{n} A_{1k}B_{k1} \\
    \sum_{k=1}^{n} A_{2k}B_{k1} \\
    \vdots \\
    \sum_{k=1}^{n} A_{nk}B_{k1} \\
\end{bmatrix} \\
$$

In [6]:
A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
B = np.array([[1, 0], [5, 2], [1, 6]])
C = A @ B
print(f'C = \n{C}')

C = 
[[14 22]
 [ 9 26]
 [35 12]]


$$
\text{矩阵的转置 (Transpose): 指的是将矩阵的行和列互换得到的新矩阵} \\
A_{ij}^T = A_{ji} \\
\quad \\
(A + Bx)^T = A^T + (Bx)^T = A^T + x^TB^T \\
(A + BCx)^T = A^T + (BCx)^T = A^T + x^TC^TB^T \\
(AB)^T = B^TA^T \\
$$


In [18]:
matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
print(f'A^T = \n{matrix.T}')

matrix_2 = np.array([[11, 12, 13], [10, 11, 14], [15, 16, 10]])
X = np.array([[3, 4, 5], [6, 7, 8], [9, 1, 2]])
print(f'(A+Bx)^T == A^T + x^T B^T? {np.array_equal((matrix + matrix_2 @ X).T, (matrix.T + X.T @ matrix_2.T))}')
print(f'(AB)^T == B^T A^T? {np.array_equal((matrix @ matrix_2).T, (matrix_2.T @ matrix.T))}')


A^T = 
[[1 0 5]
 [2 1 6]
 [3 4 0]]
(A+Bx)^T == A^T + x^T B^T? True
(AB)^T == B^T A^T? True


$$
\text{矩阵的特征值 (Eigenvalue): 指的是在矩阵变换下, 向量长度发生改变的比例} \\
\textbf{Ax} = \lambda I \textbf{x} \\
(\textbf{A} - \lambda I)\textbf{x} = 0 \\
\text{其中, A 是矩阵, x 是特征向量, I 是单位矩阵} \\
\text{对于Mx=0, 有两种方法, 一是M矩阵可逆, 那x只有唯一解0, 要使x非零解, 那M矩阵必须是不可逆也就是奇异矩阵} \\
\text{不可逆的充分必要条件即是行列式为0} \\
\det(\textbf{A} - \lambda I) = 0 \\
\lambda\text{ 是特征值, 要找的就是这个缩放后的}\lambda \\

\text{矩阵的特征向量 (Eigenvector): 指的是在矩阵变换下, 方向保持不变的向量} \\
\text{将求得的特征值代入到 }(\textbf{A} - \lambda I)\textbf{x} = 0 \text{中, 求得x即可得到对应的特征向量} \\
$$


In [8]:
matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
eig = np.linalg.eig(matrix)
print(f'matrix eigenvalues = {eig[0]}')
print(f'matrix eigenvectors = \n{eig[1]}')


matrix eigenvalues = [-5.2296696  -0.02635282  7.25602242]
matrix eigenvectors = 
[[ 0.22578016 -0.75769839 -0.49927017]
 [ 0.52634845  0.63212771 -0.46674201]
 [-0.81974424 -0.16219652 -0.72998712]]


$$
\text{对称矩阵 Symmetric Matrix} \\
\quad \\
A = \begin{bmatrix}
1 & 2 & 3 & 4 \\
2 & 5 & 6 & 7 \\
3 & 6 & 8 & 9 \\
4 & 7 & 9 & 10 \\
\end{bmatrix} = A^T \\
\quad \\
\text{对称矩阵的性质} \\
\text{1. 对称矩阵的主对角线元素都是非负数} \\
\text{2. 对称矩阵的元素满足} a_{ij} = a_{ji} \\
\text{3. 对称矩阵的特征值都是非负数} \\
\text{4. 对称矩阵的特征向量是正交的} \\
\quad \\
$$

In [9]:
A = np.array([[1, 2, 3, 4], [2, 5, 6, 7], [3, 6, 8, 9], [4, 7, 9, 10]])
eig = np.linalg.eig(A)
print(f'symmetric matrix = \n{A}')
print(f'symmetric matrix eigenvalues = {eig[0]}')
print(f'symmetric matrix eigenvectors = \n{eig[1]}')
print(f'向量1和向量2是否正交? {eig[1][:, 0] @ eig[1][:, 1].T}')
print(f'向量1和向量3是否正交? {eig[1][:, 0] @ eig[1][:, 2].T}')
print(f'向量1和向量4是否正交? {eig[1][:, 0] @ eig[1][:, 3].T}')
print(f'向量2和向量3是否正交? {eig[1][:, 1] @ eig[1][:, 2].T}')
print(f'向量2和向量4是否正交? {eig[1][:, 1] @ eig[1][:, 3].T}')
print(f'向量3和向量4是否正交? {eig[1][:, 2] @ eig[1][:, 3].T}')


symmetric matrix = 
[[ 1  2  3  4]
 [ 2  5  6  7]
 [ 3  6  8  9]
 [ 4  7  9 10]]
symmetric matrix eigenvalues = [24.06253512 -0.80548492  0.5580362   0.18491359]
symmetric matrix eigenvectors = 
[[-0.22593827 -0.72531367 -0.56047033 -0.32976505]
 [-0.44322186 -0.31846973  0.77633831 -0.3153256 ]
 [-0.57278788 -0.14246073 -0.05844028  0.805111  ]
 [-0.6514755   0.59346614 -0.28241204 -0.37897369]]
向量1和向量2是否正交? -8.326672684688674e-17
向量1和向量3是否正交? 1.3877787807814457e-16
向量1和向量4是否正交? 3.3306690738754696e-16
向量2和向量3是否正交? 1.6653345369377348e-16
向量2和向量4是否正交? 1.942890293094024e-16
向量3和向量4是否正交? -2.0539125955565396e-15


$$
\text{对角矩阵 Diagonal Matrix} \\
\quad \\
A = \begin{bmatrix}
a_{11} & 0 & \cdots & 0 \\
0 & a_{22} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & a_{nn}
\end{bmatrix} = A^T \\
\text{一定是对称矩阵}
\quad \\
$$

In [10]:
A = np.array([[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 3, 0], [0, 0, 0, 4]])
print(f'diagonal matrix = \n{A}')


diagonal matrix = 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


$$
\text{矩阵的对角化 (Diagonalization): 指的是将一个矩阵表示为其特征向量的线性组合, 其中每个特征向量都是一个基向量} \\
A = PDP^{-1} \\
\text{其中, P 是特征向量矩阵, D 是特征值矩阵} \\
$$

$$
\text{幂零矩阵 (Nilpotent Matrix): 指一个矩阵A, 满足} A^n = 0 \text{, 其中n为一个整数, 且n大于等于1} \\
\text{严格上(下)三角矩阵：主对角线及其以下(以上)元素全为0的矩阵} \\
\begin{bmatrix}
    0 & a_{12} & \cdots & a_{1n} \\
    0 & 0 & \cdots & a_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & \cdots & 0 \\
\end{bmatrix}^2 = 
\begin{bmatrix}
    0 & 0 & \cdots & 0 \\
    0 & 0 & \cdots & 0 \\
    \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & \cdots & 0 \\
\end{bmatrix}
$$

$$
\text{托普利茨矩阵 (Toeplitz Matrix)} \\
\text{托普利茨矩阵是一种特殊的方阵，其主对角线及其平行线上的元素都相同} \\
\textbf{求解偏自相关系数时就需要构建托普利茨矩阵来快速求解} \\
\text{例如: } \\
\begin{bmatrix}
1 & 2 & 3 & 6 \\
4 & 1 & 2 & 3 \\
7 & 4 & 1 & 2 \\
10 & 7 & 4 & 1 \\
\end{bmatrix}
$$

In [11]:
A = np.array([[1, 2, 3, 6],
              [4, 1, 2, 3],
              [7, 4, 1, 2],
              [10, 7, 4, 1]])

B = scipy.linalg.toeplitz([1, 4, 7, 10], [1, 2, 3, 6])
print(f'A and B are equal: {np.array_equal(A, B)}')

A and B are equal: True


$$
\text{循环矩阵 (Circulant Matrix)} \\
\text{循环矩阵是一种特殊的方阵，也是特殊的托普利茨矩阵，其主对角线及其平行线上的元素都相同} \\
\text{例如: } \\
\begin{bmatrix}
1 & 2 & 3 & 4 \\
4 & 1 & 2 & 3 \\
3 & 4 & 1 & 2 \\
2 & 3 & 4 & 1 \\
\end{bmatrix}
$$

In [12]:
print(f'循环矩阵 = \n{scipy.linalg.circulant([1, 4, 3, 2])}')

循环矩阵 = 
[[1 2 3 4]
 [4 1 2 3]
 [3 4 1 2]
 [2 3 4 1]]
