$$
判断矩阵 \\
\begin{array}{|c|c|c|c|}
\hline
 & 属性A & 属性B & 属性C \\
\hline
属性A & 1 & 2 & 3 \\
\hline
属性B & \frac{1}{2} & 1 & 2 \\
\hline
属性C & \frac{1}{3} & \frac{1}{2} & 1 \\
\hline
\end{array}
\newline
注意：这里的所有判断标准出自主观，即判断矩阵的元素都是主观判断的结果。\\
$$

In [2]:
import numpy as np

m = np.array([[1, 2, 3], [1/2, 1, 2], [1/3, 1/2, 1]])
m

array([[1.        , 2.        , 3.        ],
       [0.5       , 1.        , 2.        ],
       [0.33333333, 0.5       , 1.        ]])

$$
下面有几种权重计算方式 \\
\text{1. } 列算术平均 \\
\text{2. } 列几何平均 \\
\text{3. } 特征向量
$$

$$
\text{矩阵的秩 (Rank) r(A): 指的是有效信息的行. 经过初等行变换之后, 剩下的个数就为这个矩阵的秩} \\
$$


$$
\text{矩阵的迹 (Trace) tr(A): 指方阵对角线上所有元素之和} \\
tr(A) = \sum_{i=1}^n A_{ii} \\
$$


$$
\text{矩阵的行列式 (Determinant): 指的是一个方阵的特征值的乘积, 可以用于判断矩阵是否可逆, 以及缩放比例} \\
det(A) = GaussianElimination(A) -> \text{最终得到的上三角矩阵的对角线元素的乘积} \\
det(A) != 0 \text{ 时, 矩阵可逆, 且缩放比例为 det(A)} \\
det(A) = 0 \text{ 时, 矩阵变换后, 会导致降维, 继而不可逆} \\
$$


$$
\text{矩阵的逆 (Inverse): 指的是使得是n阶方阵A乘以其逆矩阵得到单位矩阵I} \\
\text{Gauss-Jordan 消元法 (初等变换): 是一种用于求解线性方程组的方法, 同时也可以用于求矩阵的逆} \\
[A|I] = [I|A^{-1}] \\
例子: \\
[A|I] = \begin{bmatrix}
1 & 2 & 3 & 1 & 0 & 0 \\
0 & 1 & 4 & 0 & 1 & 0 \\
5 & 6 & 0 & 0 & 0 & 1 \\
\end{bmatrix} \\
[I|A^{-1}] = \begin{bmatrix}
1 & 0 & 0 & -24 & 18 & 5 \\
0 & 1 & 0 & 20 & -15 & -4 \\
0 & 0 & 1 & -5 & 4 & 1 \\
\end{bmatrix} \\
$$


$$
\text{矩阵的转置 (Transpose): 指的是将矩阵的行和列互换得到的新矩阵} \\
A_{ij}^T = A_{ji} \\
$$


$$
\text{矩阵的特征值 (Eigenvalue): 指的是在矩阵变换下, 向量长度发生改变的比例} \\
\textbf{Ax} = \lambda I \textbf{x} \\
\textbf{A} - \lambda I = 0 \\
\text{其中, A 是矩阵, x 是特征向量, I 是单位矩阵} \\
\det(\textbf{A} - \lambda I) = 0 \\
\lambda\text{ 是特征值, 要找的就是这个缩放后的}\lambda \\

\text{矩阵的特征向量 (Eigenvector): 指的是在矩阵变换下, 方向保持不变的向量} \\
\text{将求得的特征值代入到 }\textbf{A} - \lambda I = 0 \text{中, 即可得到对应的特征向量} \\
$$


$$
\text{矩阵的对角化 (Diagonalization): 指的是将一个矩阵表示为其特征向量的线性组合, 其中每个特征向量都是一个基向量} \\
A = PDP^{-1} \\
\text{其中, P 是特征向量矩阵, D 是特征值矩阵} \\
$$

In [6]:
np.mean(m, axis=0)

array([0.61111111, 1.16666667, 2.        ])

$$
计算判断矩阵特征向量 \\

$$

In [3]:
eig_values, eig_vectors = np.linalg.eig(m)

In [4]:
eig_values

array([ 3.00920271+0.j      , -0.00460136+0.166348j,
       -0.00460136-0.166348j])

In [5]:
eig_vectors

array([[ 0.84679693+0.j        , -0.84679693+0.j        ,
        -0.84679693-0.j        ],
       [ 0.46601031+0.j        ,  0.23300515-0.40357677j,
         0.23300515+0.40357677j],
       [ 0.25645536+0.j        ,  0.12822768+0.22209685j,
         0.12822768-0.22209685j]])

$$
一致性检验 \\

$$