$$
判断矩阵 / 正互反矩阵 (不是一致矩阵) \\
\begin{array}{|c|c|c|c|c|}
\hline
 & 粉丝数 & 颜值 & 作品质量 & 作品数量 \\
\hline
粉丝数 & 1 & 2 & 3 & 5 \\
\hline
颜值 & \frac{1}{2} & 1 & \frac{1}{2} & 2 \\
\hline
作品质量 & \frac{1}{3} & 2 & 1 & \frac{1}{2} \\
\hline
作品数量 & \frac{1}{5} & \frac{1}{2} & 2 & 1 \\
\hline
\end{array}
\newline
注意：这里的所有判断标准出自主观，即判断矩阵的元素都是主观判断的结果。\\
$$

In [86]:
import numpy as np

m = np.array([[1, 2, 3, 5], [1/2, 1, 1/2, 2], [1/3, 2, 1, 1/2], [1/5, 1/2, 2, 1]])


$$
\text{矩阵的秩 (Rank) r(A): 指的是有效信息的行. 经过初等行变换之后, 剩下的个数就为这个矩阵的秩} \\
$$


$$
矩阵的零度 (Nullity): 指的是矩阵的解空间的维数 \\
和秩的关系：\\
\text{Rank(A) + Nullity(A) = n} \\
\text{其中，n 是矩阵的列数} \\
$$


$$
\text{矩阵的迹 (Trace) tr(A): 指方阵对角线上所有元素之和} \\
tr(A) = \sum_{i=1}^n A_{ii} \\
当A矩阵的秩为1时, 零度为n-1, 也就是说除一个元素外, 其他元素都为0, 那么 \\
tr(A) = \lambda + 0 + 0 + ... + 0 \\
tr(A) = \lambda \\
\text{其中} \lambda \text{为A的一个特征值} \\
$$


$$
\text{矩阵的行列式 (Determinant): 指的是一个方阵的特征值的乘积, 可以用于判断矩阵是否可逆, 以及缩放比例} \\
det(A) = GaussianElimination(A) -> \text{最终得到的上三角矩阵的对角线元素的乘积} \\
det(A) != 0 \text{ 时, 矩阵可逆, 且缩放比例为 det(A)} \\
det(A) = 0 \text{ 时, 矩阵变换后, 会导致降维, 继而不可逆} \\
$$


$$
\text{矩阵的逆 (Inverse): 指的是使得是n阶方阵A乘以其逆矩阵得到单位矩阵I} \\
\text{Gauss-Jordan 消元法 (初等变换): 是一种用于求解线性方程组的方法, 同时也可以用于求矩阵的逆} \\
[A|I] = [I|A^{-1}] \\
例子: \\
[A|I] = \begin{bmatrix}
1 & 2 & 3 & 1 & 0 & 0 \\
0 & 1 & 4 & 0 & 1 & 0 \\
5 & 6 & 0 & 0 & 0 & 1 \\
\end{bmatrix} \\
[I|A^{-1}] = \begin{bmatrix}
1 & 0 & 0 & -24 & 18 & 5 \\
0 & 1 & 0 & 20 & -15 & -4 \\
0 & 0 & 1 & -5 & 4 & 1 \\
\end{bmatrix} \\
$$


$$
矩阵乘法的数学通式 \\
C_{ij} = \sum_{k=1}^{n} A_{ik}B_{kj} \\
C = \begin{bmatrix}
    \sum_{k=1}^{n} A_{1k}B_{k1} & \sum_{k=1}^{n} A_{1k}B_{k2} & \cdots & \sum_{k=1}^{n} A_{1k}B_{kn} \\
    \sum_{k=1}^{n} A_{2k}B_{k1} & \sum_{k=1}^{n} A_{2k}B_{k2} & \cdots & \sum_{k=1}^{n} A_{2k}B_{kn} \\
    \vdots & \vdots & \ddots & \vdots \\
    \sum_{k=1}^{n} A_{nk}B_{k1} & \sum_{k=1}^{n} A_{nk}B_{k2} & \cdots & \sum_{k=1}^{n} A_{nk}B_{kn} \\
\end{bmatrix} \\
如果B是列向量 \\
C = \begin{bmatrix}
    \sum_{k=1}^{n} A_{1k}B_{k1} \\
    \sum_{k=1}^{n} A_{2k}B_{k1} \\
    \vdots \\
    \sum_{k=1}^{n} A_{nk}B_{k1} \\
\end{bmatrix} \\
$$

$$
\text{矩阵的转置 (Transpose): 指的是将矩阵的行和列互换得到的新矩阵} \\
A_{ij}^T = A_{ji} \\
$$


$$
\text{矩阵的特征值 (Eigenvalue): 指的是在矩阵变换下, 向量长度发生改变的比例} \\
\textbf{Ax} = \lambda I \textbf{x} \\
(\textbf{A} - \lambda I)\textbf{x} = 0 \\
\text{其中, A 是矩阵, x 是特征向量, I 是单位矩阵} \\
\text{对于Mx=0, 有两种方法, 一是M矩阵可逆, 那x只有唯一解0, 要使x非零解, 那M矩阵必须是不可逆也就是奇异矩阵} \\
\text{不可逆的充分必要条件即是行列式为0} \\
\det(\textbf{A} - \lambda I) = 0 \\
\lambda\text{ 是特征值, 要找的就是这个缩放后的}\lambda \\

\text{矩阵的特征向量 (Eigenvector): 指的是在矩阵变换下, 方向保持不变的向量} \\
\text{将求得的特征值代入到 }(\textbf{A} - \lambda I)\textbf{x} = 0 \text{中, 求得x即可得到对应的特征向量} \\
$$


$$
\text{矩阵的对角化 (Diagonalization): 指的是将一个矩阵表示为其特征向量的线性组合, 其中每个特征向量都是一个基向量} \\
A = PDP^{-1} \\
\text{其中, P 是特征向量矩阵, D 是特征值矩阵} \\
$$

$$
\text{幂零矩阵 (Nilpotent Matrix): 指一个矩阵A, 满足} A^n = 0 \text{, 其中n为一个整数, 且n大于等于1} \\
\text{严格上(下)三角矩阵：主对角线及其以下(以上)元素全为0的矩阵} \\
\begin{bmatrix}
    0 & a_{12} & \cdots & a_{1n} \\
    0 & 0 & \cdots & a_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & \cdots & 0 \\
\end{bmatrix}^2 = 
\begin{bmatrix}
    0 & 0 & \cdots & 0 \\
    0 & 0 & \cdots & 0 \\
    \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & \cdots & 0 \\
\end{bmatrix}
$$

$$
一致性检验 \\
\text{Consistency Index (CI) = }\frac{\lambda_{max} - n}{n - 1} \\
\text{CI是一致性指标} \\
\text{Random Index (RI) 是随机一致性指标} \\
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|}
\hline
n & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 \\
\hline
RI & 0 & 0 & 0.52 & 0.89 & 1.12 & 1.26 & 1.36 & 1.41 & 1.46 & 1.49 & 1.52 \\
\hline
\end{array}\\
\text{Consistency Ratio (CR) = }\frac{CI}{RI} \\
\text{CR是一致性比例, 当CR小于0.1时, 认为矩阵是一致的, 越小越好} \\
$$

In [87]:
eigvals, eigvecs = np.linalg.eig(m)
eigvals

array([ 4.46724532+0.j        , -0.08901902+0.j        ,
       -0.18911315+1.42051623j, -0.18911315-1.42051623j])

In [88]:
def consistency_analysis(eigvals):
    # 去掉虚数
    eigvals = eigvals.real
    CI = (eigvals.max() - eigvals.size) / (eigvals.size - 1)
    RI = {1: 0, 2: 0, 3: 0.52, 4: 0.89, 5: 1.12, 6: 1.26, 7: 1.36, 8: 1.41, 9: 1.46, 10: 1.49, 11: 1.52}
    CR = CI / RI[eigvals.size]
    print(f'一致性指标 CI = {CI:.4f}\n随机一致性指标 RI = {RI[eigvals.size]:.4f}\n一致性比率 CR = {CR:.4f}')
    if CR == 0.1:
        print('判断矩阵是一致矩阵')
    elif CR < 0.1:
        print('判断矩阵是一致的')
    else:
        print('判断矩阵不是一致的, 建议重新构造判断矩阵')

consistency_analysis(eigvals)


一致性指标 CI = 0.1557
随机一致性指标 RI = 0.8900
一致性比率 CR = 0.1750
判断矩阵不是一致的, 建议重新构造判断矩阵


In [89]:
m = np.array([[1, 2, 3, 5], [1/2, 1, 1/2, 2], [1/3, 2, 1, 2], [1/5, 1/2, 1/2, 1]])
eigvals, eigvecs = np.linalg.eig(m)
consistency_analysis(eigvals)

一致性指标 CI = 0.0376
随机一致性指标 RI = 0.8900
一致性比率 CR = 0.0423
判断矩阵是一致的


$$
下面有三种权重计算方式 \\
$$

$$
\text{1. } 列算术平均 \\
求得每列的总和，再将每列的元素除以总和，再计算每列的总和，最后除以阶数 \\
\textbf{w}_i = \frac{1}{n} \sum_{j=1}^n \frac{a_{ij}}{\sum_{k=1}^n a_{kj}}
$$

In [90]:
col_sums = np.sum(m, axis=0)
weight_arithmic_mean_m = m / col_sums
weight_arithmic_mean_m

array([[0.49180328, 0.36363636, 0.6       , 0.5       ],
       [0.24590164, 0.18181818, 0.1       , 0.2       ],
       [0.16393443, 0.36363636, 0.2       , 0.2       ],
       [0.09836066, 0.09090909, 0.1       , 0.1       ]])

In [91]:
weight_arithmic_mean_m.sum(axis=1)

array([1.95543964, 0.72771982, 0.92757079, 0.38926975])

In [92]:
weight_arithmic_mean_m.sum(axis=1) / weight_arithmic_mean_m.shape[1]

array([0.48885991, 0.18192996, 0.2318927 , 0.09731744])

$$
\text{2. } 列几何平均 \\
按行相乘，再对每个分量开n次方，再对向量归一化 \\
\textbf{w}_i = \frac{\left( \prod_{j=1}^n m_{ij} \right)^{\frac{1}{n}}}{\sum_{k=1}^n \left( \prod_{j=1}^n m_{kj} \right)^{\frac{1}{n}}}
$$

In [93]:
row_product = np.prod(m, axis=1)
weight_geometric_mean_m = row_product**(1/m.shape[1])
weight_geometric_mean_m

array([2.34034732, 0.84089642, 1.07456993, 0.4728708 ])

In [96]:
weight_geometric_mean_m / weight_geometric_mean_m.sum(axis=0)

array([0.49492567, 0.17782883, 0.22724501, 0.1000005 ])

$$
\text{3. } 特征向量 \\
\textbf{w}_i = \frac{\lambda_i}{\sum_{j=1}^n \lambda_j}
$$